---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    app.dekorate.io/vcs-url: "<<unknown>>"
    app.dekorate.io/commit-id: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "demo-user"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  name: "demo-user"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    app.dekorate.io/vcs-url: "<<unknown>>"
    app.dekorate.io/commit-id: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "demo-user"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  name: "demo-user"
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: "demo-user"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  type: "ClusterIP"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  annotations:
    app.dekorate.io/vcs-url: "<<unknown>>"
    app.dekorate.io/commit-id: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "demo-user"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  name: "demo-user:view"
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: "view"
subjects:
  - kind: "ServiceAccount"
    name: "demo-user"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.dekorate.io/vcs-url: "<<unknown>>"
    app.dekorate.io/commit-id: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "demo-user"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  name: "demo-user"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "demo-user"
      app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  template:
    metadata:
      annotations:
        app.dekorate.io/vcs-url: "<<unknown>>"
        app.dekorate.io/commit-id: "<<unknown>>"
      labels:
        app.kubernetes.io/name: "demo-user"
        app.kubernetes.io/version: "0.0.1-SNAPSHOT"
    spec:
      containers:
        - env:
            - name: "KUBERNETES_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
          image: "fsalikutluk/demo-user:0.0.1-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          name: "demo-user"
          ports:
            - containerPort: 8080
              name: "http"
              protocol: "TCP"
      serviceAccount: "demo-user"
